services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cine
      MYSQL_USER: cine_user
      MYSQL_PASSWORD: cine_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./cine.sql:/docker-entrypoint-initdb.d/cine.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

  api:
    build:
      context: ./api-cine
      dockerfile: Dockerfile
    container_name: api
    restart: always
    working_dir: /var/www
    volumes:
      - ./api-cine:/var/www
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cine
      DB_USERNAME: cine_user
      DB_PASSWORD: cine_pass
    ports:
      - "8000:8000"
    depends_on:
      - db

  sveltekit:
    build:
      context: ./absolute-cinema
      dockerfile: Dockerfile
    container_name: svelte
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./absolute-cinema:/app
    depends_on:
      - api

volumes:
  db_data:
